In [8]:
import pickle
import csv

In [2]:
with open('msa_dict.pkl', 'rb') as f:
    data = pickle.load(f)

In [9]:
import pandas as pd
df = pd.read_csv('LGBT_cleaned.csv')

In [10]:
df

,STATE,MSA ABBREVIATED NAME,% LGBT,# LGBT (Total),RANGE
0,Arizona,"Phoenix-Mesa-Scottsdale, AZ",4.30%,"146,000","135,000, 158,000"
1,Arizona,"Tucson, AZ",4.70%,"37,000","33,000, 43,000"
2,California,"Los Angeles, CA",5.10%,"523,000","499,000, 548,000"
3,California,"Riverside-San Bernardino-Ontario, CA",4.00%,"133,000","122,000, 145,000"
4,California,"Sacramento, CA",4.40%,"77,000","69,000, 85,000"
5,California,"San Diego, CA",4.50%,"115,000","105,000, 126,000"
6,California,"San Francisco/Bay Area, CA",6.70%,"247,000","232,000, 262,000"
7,California,"San Jose-Sunnyvale-Santa Clara, CA",3.80%,"58,000","51,000, 67,000"
8,Colorado,"Denver, CO",4.80%,"103,000","95,000, 112,000"
9,Connecticut,"Hartford-West Hartford-East Hartford, CT",4.60%,"44,000","38,000, 51,000"
10,District of Columbia,"Washington, DC (DC-MD-VA)",4.50%,"209,000","197,000, 222,000"
11,Florida,"Miami, FL",4.50%,"214,000","199,000, 230,000"
12,Florida,"Jacksonville, FL",4.20%,"47,000","41,000, 54,000"
13,Florida,"Orlando, FL",5.00%,"93,000","84,000, 103,000"
14,Florida,"Tampa-St. Petersburg-Clearwater, FL",4.80%,"113,000","104,000, 123,000"
15,Georgia,"Atlanta, GA",4.60%,"194,000","182,000, 207,000"
16,Illinois,"Chicago, IL (IL-IN-WI)",4.10%,"298,000","280,000, 316,000"
17,Indiana,"Indianapolis, IN",4.60%,"68,000","61,000, 76,000"
18,Kentucky,"Louisville, KY (KY-IN)",4.20%,"42,000","36,000, 48,000"
19,Louisiana,"New Orleans, LA",4.70%,"46,000","40,000, 53,000"
20,Maryland,"Baltimore, MD",4.10%,"89,000","81,000, 98,000"
21,Massachusetts,"Worcester, MA (MA-CT)",4.50%,"33,000","28,000, 39,000"
22,Massachusetts,"Boston, MA (MA-NH)",4.90%,"186,000","174,000, 198,000"
23,Michigan,"Detroit, MI",3.90%,"131,000","119,000, 143,000"
24,Minnesota,"Minneapolis-St. Paul, MN (MN-WI)",4.20%,"112,000","103,000, 121,000"
25,Missouri,"St. Louis, MO (MO-IL)",3.70%,"79,000","71,000, 88,000"
26,Missouri,"Kansas City, MO (MO-KS)",3.80%,"60,000","53,000, 67,000"
27,Nebraska,"Omaha-Council Bluffs, NE (NE-IA)",3.40%,"23,000","20,000, 27,000"
28,Nevada,"Las Vegas, NV",5.10%,"82,000","73,000, 92,000"
29,New Mexico,"Albuquerque, NM",4.40%,"31,000","27,000, 36,000"
30,New York,"Albany, NY",4.00%,"28,000","24,000, 33,000"
31,New York,"Buffalo, NY",4.10%,"37,000","32,000, 42,000"
32,New York,"Rochester, NY",4.30%,"37,000","32,000, 43,000"
33,New York,"New York, NY (NY-NJ-PA)",4.50%,"706,000","681,000, 733,000"
34,North Carolina,"Raleigh, NC",3.30%,"32,000","27,000, 37,000"
35,North Carolina,"Charlotte, NC (NC-SC)",4.00%,"74,000","66,000, 83,000"
36,Ohio,"Cleveland, OH",3.80%,"62,000","54,000, 70,000"
37,Ohio,"Columbus, OH",4.40%,"67,000","60,000, 76,000"
38,Ohio,"Cincinnati, OH (OH-KY-IN)",3.60%,"60,000","53,000, 67,000"
39,Oklahoma,"Oklahoma City, OK",3.80%,"39,000","34,000, 45,000"
40,Oklahoma,"Tulsa, OK",4.10%,"30,000","26,000, 35,000"
41,Oregon,"Portland, OR (OR-WA)",6.00%,"112,000","104,000, 121,000"
42,Pennsylvania,"Pittsburgh, PA",3.30%,"63,000","57,000, 70,000"
43,Pennsylvania,"Philadelphia, PA (PA-NJ-DE-MD)",4.20%,"198,000","185,000, 212,000"
44,Rhode Island,"Providence, RI (RI-MA)",4.50%,"58,000","51,000, 65,000"
45,Tennessee,"Nashville, TN",3.70%,"52,000","46,000, 59,000"
46,Texas,"Austin-Round Rock, TX",5.90%,"90,000","82,000, 99,000"
47,Texas,"Dallas-Fort Worth-Arlington, TX",4.00%,"211,000","197,000, 226,000"
48,Texas,"Houston, TX",3.50%,"169,000","156,000, 183,000"
49,Texas,"San Antonio, TX",4.40%,"78,000","70,000, 88,000"
50,Utah,"Salt Lake City, UT",4.70%,"39,000","35,000, 45,000"
51,Virginia,"Richmond, VA",4.10%,"40,000","35,000, 47,000"
52,Virginia,"Virginia Beach-Norfolk-Newport News, VA",4.10%,"55,000","48,000, 62,000"
53,Washington,"Seattle-Tacoma-Bellevue, WA",5.20%,"152,000","141,000, 163,000"
54,Wisconsin,"Milwaukee-Waukesha-West Allis, WI",3.50%,"42,000","37,000, 48,000"

In [11]:
data

{122: 'Montgomery, AL Metro Area',
 312: 'Daphne-Fairhope-Foley, AL Metro Area',
 48: 'Birmingham-Hoover, AL Metro Area',
 299: 'Anniston-Oxford, AL Metro Area',
 245: 'Florence-Muscle Shoals, AL Metro Area',
 329: 'Gadsden, AL Metro Area',
 263: 'Dothan, AL Metro Area',
 197: 'Tuscaloosa, AL Metro Area',
 268: 'Decatur, AL Metro Area',
 339: 'Auburn-Opelika, AL Metro Area',
 150: 'Huntsville, AL Metro Area',
 128: 'Mobile, AL Metro Area',
 164: 'Columbus, GA-AL Metro Area',
 144: 'Anchorage, AK Metro Area',
 368: 'Fairbanks, AK Metro Area',
 272: 'Sierra Vista-Douglas, AZ Metro Area',
 284: 'Flagstaff, AZ Metro Area',
 12: 'Phoenix-Mesa-Chandler, AZ Metro Area',
 246: 'Lake Havasu City-Kingman, AZ Metro Area',
 56: 'Tucson, AZ Metro Area',
 252: 'Prescott Valley-Prescott, AZ Metro Area',
 213: 'Yuma, AZ Metro Area',
 135: 'Fayetteville-Springdale-Rogers, AR Metro Area',
 309: 'Pine Bluff, AR Metro Area',
 330: 'Jonesboro, AR Metro Area',
 190: 'Fort Smith, AR-OK Metro Area',
 44: 'Memphis, TN-MS-AR Metro Area',
 78: 'Little Rock-North Little Rock-Conway, AR Metro Area',
 352: 'Hot Springs, AR Metro Area',
 239: 'Texarkana, TX-AR Metro Area',
 11: 'San Francisco-Oakland-Berkeley, CA Metro Area',
 166: 'Chico, CA Metro Area',
 28: 'Sacramento-Roseville-Folsom, CA Metro Area',
 60: 'Fresno, CA Metro Area',
 290: 'El Centro, CA Metro Area',
 80: 'Bakersfield, CA Metro Area',
 332: 'Hanford-Corcoran, CA Metro Area',
 2: 'Los Angeles-Long Beach-Anaheim, CA Metro Area',
 333: 'Madera, CA Metro Area',
 209: 'Merced, CA Metro Area',
 154: 'Salinas, CA Metro Area',
 269: 'Napa, CA Metro Area',
 16: 'Riverside-San Bernardino-Ontario, CA Metro Area',
 36: 'San Jose-Sunnyvale-Santa Clara, CA Metro Area',
 22: 'San Diego-Chula Vista-Carlsbad, CA Metro Area',
 90: 'Stockton, CA Metro Area',
 200: 'San Luis Obispo-Paso Robles, CA Metro Area',
 110: 'Santa Maria-Santa Barbara, CA Metro Area',
 174: 'Santa Cruz-Watsonville, CA Metro Area',
 228: 'Redding, CA Metro Area',
 123: 'Vallejo, CA Metro Area',
 91: 'Santa Rosa-Petaluma, CA Metro Area',
 112: 'Modesto, CA Metro Area',
 260: 'Yuba City, CA Metro Area',
 130: 'Visalia, CA Metro Area',
 86: 'Oxnard-Thousand Oaks-Ventura, CA Metro Area',
 21: 'Denver-Aurora-Lakewood, CO Metro Area',
 165: 'Boulder, CO Metro Area',
 92: 'Colorado Springs, CO Metro Area',
 170: 'Fort Collins, CO Metro Area',
 308: 'Grand Junction, CO Metro Area',
 223: 'Pueblo, CO Metro Area',
 181: 'Greeley, CO Metro Area',
 55: 'Bridgeport-Stamford-Norwalk, CT Metro Area',
 43: 'Hartford-East Hartford-Middletown, CT Metro Area',
 59: 'New Haven-Milford, CT Metro Area',
 184: 'Norwich-New London, CT Metro Area',
 53: 'Worcester, MA-CT Metro Area',
 350: 'Dover, DE Metro Area',
 4: 'Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metro Area',
 138: 'Salisbury, MD-DE Metro Area',
 7: 'Washington-Arlington-Alexandria, DC-VA-MD-WV Metro Area',
 167: 'Gainesville, FL Metro Area',
 50: 'Jacksonville, FL Metro Area',
 277: 'Panama City, FL Metro Area',
 118: 'Palm Bay-Melbourne-Titusville, FL Metro Area',
 8: 'Miami-Fort Lauderdale-Pompano Beach, FL Metro Area',
 285: 'Punta Gorda, FL Metro Area',
 327: 'Homosassa Springs, FL Metro Area',
 176: 'Naples-Marco Island, FL Metro Area',
 133: 'Pensacola-Ferry Pass-Brent, FL Metro Area',
 113: 'Deltona-Daytona Beach-Ormond Beach, FL Metro Area',
 152: 'Tallahassee, FL Metro Area',
 18: 'Tampa-St. Petersburg-Clearwater, FL Metro Area',
 336: 'Sebring-Avon Park, FL Metro Area',
 313: 'Sebastian-Vero Beach, FL Metro Area',
 46: 'Orlando-Kissimmee-Sanford, FL Metro Area',
 76: 'Cape Coral-Fort Myers, FL Metro Area',
 82: 'North Port-Sarasota-Bradenton, FL Metro Area',
 180: 'Ocala, FL Metro Area',
 153: 'Port St. Lucie, FL Metro Area',
 198: 'Crestview-Fort Walton Beach-Destin, FL Metro Area',
 103: 'Lakeland-Winter Haven, FL Metro Area',
 383: 'The Villages, FL Metro Area',
 13: 'Atlanta-Sandy Springs-Alpharetta, GA Metro Area',
 188: 'Macon-Bibb County, GA Metro Area',
 351: 'Brunswick, GA Metro Area',
 294: 'Valdosta, GA Metro Area',
 149: 'Savannah, GA Metro Area',
 96: 'Augusta-Richmond County, GA-SC Metro Area',
 95: 'Chattanooga, TN-GA Metro Area',
 259: 'Athens-Clarke County, GA Metro Area',
 267: 'Albany, GA Metro Area',
 375: 'Rome, GA Metro Area',
 302: 'Gainesville, GA Metro Area',
 317: 'Warner Robins, GA Metro Area',
 384: 'Hinesville, GA Metro Area',
 287: 'Dalton, GA Metro Area',
 65: 'Urban Honolulu, HI Metro Area',
 334: 'Kahului-Wailuku-Lahaina, HI Metro Area',
 126: 'Boise City, ID Metro Area',
 357: 'Pocatello, ID Metro Area',
 322: 'Idaho Falls, ID Metro Area',
 311: 'Logan, UT-ID Metro Area',
 354: 'Twin Falls, ID Metro Area',
 361: "Coeur d'Alene, ID Metro Area",
 373: 'Lewiston, ID-WA Metro Area',
 341: 'Cape Girardeau, MO-IL Metro Area',
 17: 'St. Louis, MO-IL Metro Area',
 121: 'Rockford, IL Metro Area',
 189: 'Champaign-Urbana, IL Metro Area',
 3: 'Chicago-Naperville-Elgin, IL-IN-WI Metro Area',
 107: 'Peoria, IL Metro Area',
 109: 'Davenport-Moline-Rock Island, IA-IL Metro Area',
 242: 'Carbondale-Marion, IL Metro Area',
 324: 'Kankakee, IL Metro Area',
 266: 'Bloomington, IL Metro Area',
 282: 'Decatur, IL Metro Area',
 169: 'Springfield, IL Metro Area',
 362: 'Danville, IL Metro Area',
 117: 'Fort Wayne, IN Metro Area',
 372: 'Columbus, IN Metro Area',
 215: 'Lafayette-West Lafayette, IN Metro Area',
 33: 'Indianapolis-Carmel-Anderson, IN Metro Area',
 42: 'Louisville/Jefferson County, KY-IN Metro Area',
 177: 'Terre Haute, IN Metro Area',
 24: 'Cincinnati, OH-KY-IN Metro Area',
 275: 'Muncie, IN Metro Area',
 240: 'Elkhart-Goshen, IN Metro Area',
 360: 'Kokomo, IN Metro Area',
 337: 'Michigan City-La Porte, IN Metro Area',
 262: 'Bloomington, IN Metro Area',
 136: 'Evansville, IN-KY Metro Area',
 129: 'South Bend-Mishawaka, IN-MI Metro Area',
 179: 'Cedar Rapids, IA Metro Area',
 225: 'Waterloo-Cedar Falls, IA Metro Area',
 331: 'Ames, IA Metro Area',
 84: 'Des Moines-West Des Moines, IA Metro Area',
 335: 'Dubuque, IA Metro Area',
 47: 'Omaha-Council Bluffs, NE-IA Metro Area',
 300: 'Iowa City, IA Metro Area',
 219: 'Sioux City, IA-NE-SD Metro Area',
 79: 'Wichita, KS Metro Area',
 270: 'St. Joseph, MO-KS Metro Area',
 364: 'Lawrence, KS Metro Area',
 307: 'Manhattan, KS Metro Area',
 175: 'Topeka, KS Metro Area',
 25: 'Kansas City, MO-KS Metro Area',
 265: 'Bowling Green, KY Metro Area',
 102: 'Lexington-Fayette, KY Metro Area',
 116: 'Huntington-Ashland, WV-KY-OH Metro Area',
 195: 'Clarksville, TN-KY Metro Area',
 325: 'Owensboro, KY Metro Area',
 276: 'Elizabethtown-Fort Knox, KY Metro Area',
 114: 'Lafayette, LA Metro Area',
 74: 'Baton Rouge, LA Metro Area',
 119: 'Shreveport-Bossier City, LA Metro Area',
 206: 'Lake Charles, LA Metro Area',
 256: 'Alexandria, LA Metro Area',
 37: 'New Orleans-Metairie, LA Metro Area',
 212: 'Houma-Thibodaux, LA Metro Area',
 196: 'Monroe, LA Metro Area',
 358: 'Hammond, LA Metro Area',
 348: 'Lewiston-Auburn, ME Metro Area',
 99: 'Portland-South Portland, ME Metro Area',
 249: 'Bangor, ME Metro Area',
 344: 'Cumberland, MD-WV Metro Area',
 20: 'Baltimore-Columbia-Towson, MD Metro Area',
 379: 'California-Lexington Park, MD Metro Area',
 182: 'Hagerstown-Martinsburg, MD-WV Metro Area',
 173: 'Barnstable Town, MA Metro Area',
 211: 'Pittsfield, MA Metro Area',
 34: 'Providence-Warwick, RI-MA Metro Area',
 9: 'Boston-Cambridge-Newton, MA-NH Metro Area',
 72: 'Springfield, MA Metro Area',
 328: 'Bay City, MI Metro Area',
 222: 'Niles, MI Metro Area',
 248: 'Battle Creek, MI Metro Area',
 85: 'Lansing-East Lansing, MI Metro Area',
 94: 'Flint, MI Metro Area',
 57: 'Grand Rapids-Kentwood, MI Metro Area',
 229: 'Jackson, MI Metro Area',
 171: 'Kalamazoo-Portage, MI Metro Area',
 6: 'Detroit-Warren-Dearborn, MI Metro Area',
 365: 'Midland, MI Metro Area',
 243: 'Monroe, MI Metro Area',
 226: 'Muskegon, MI Metro Area',
 183: 'Saginaw, MI Metro Area',
 140: 'Ann Arbor, MI Metro Area',
 15: 'Minneapolis-St. Paul-Bloomington, MN-WI Metro Area',
 238: 'St. Cloud, MN Metro Area',
 359: 'Mankato, MN Metro Area',
 125: 'Duluth, MN-WI Metro Area',
 216: 'Fargo, ND-MN Metro Area',
 185: 'Rochester, MN Metro Area',
 280: 'La Crosse-Onalaska, WI-MN Metro Area',
 315: 'Grand Forks, ND-MN Metro Area',
 87: 'Jackson, MS Metro Area',
 271: 'Hattiesburg, MS Metro Area',
 143: 'Gulfport-Biloxi, MS Metro Area',
 258: 'Columbia, MO Metro Area',
 261: 'Jefferson City, MO Metro Area',
 134: 'Springfield, MO Metro Area',
 217: 'Joplin, MO Metro Area',
 233: 'Billings, MT Metro Area',
 347: 'Great Falls, MT Metro Area',
 342: 'Missoula, MT Metro Area',
 371: 'Grand Island, NE Metro Area',
 160: 'Lincoln, NE Metro Area',
 31: 'Las Vegas-Henderson-Paradise, NV Metro Area',
 108: 'Reno, NV Metro Area',
 382: 'Carson City, NV Metro Area',
 131: 'Manchester-Nashua, NH Metro Area',
 186: 'Atlantic City-Hammonton, NJ Metro Area',
 1: 'New York-Newark-Jersey City, NY-NJ-PA Metro Area',
 367: 'Ocean City, NJ Metro Area',
 279: 'Vineland-Bridgeton, NJ Metro Area',
 145: 'Trenton-Princeton, NJ Metro Area',
 61: 'Allentown-Bethlehem-Easton, PA-NJ Metro Area',
 62: 'Albuquerque, NM Metro Area',
 234: 'Las Cruces, NM Metro Area',
 286: 'Farmington, NM Metro Area',
 273: 'Santa Fe, NM Metro Area',
 51: 'Albany-Schenectady-Troy, NY Metro Area',
 141: 'Binghamton, NY Metro Area',
 314: 'Elmira, NY Metro Area',
 67: 'Poughkeepsie-Newburgh-Middletown, NY Metro Area',
 41: 'Buffalo-Cheektowaga, NY Metro Area',
 142: 'Utica-Rome, NY Metro Area',
 291: 'Watertown-Fort Drum, NY Metro Area',
 45: 'Rochester, NY Metro Area',
 73: 'Syracuse, NY Metro Area',
 366: 'Ithaca, NY Metro Area',
 201: 'Kingston, NY Metro Area',
 296: 'Glens Falls, NY Metro Area',
 255: 'Burlington, NC Metro Area',
 147: 'Hickory-Lenoir-Morganton, NC Metro Area',
 27: 'Charlotte-Concord-Gastonia, NC-SC Metro Area',
 148: 'Myrtle Beach-Conway-North Myrtle Beach, SC-NC Metro Area',
 120: 'Asheville, NC Metro Area',
 35: 'Virginia Beach-Norfolk-Newport News, VA-NC Metro Area',
 106: 'Durham-Chapel Hill, NC Metro Area',
 363: 'New Bern, NC Metro Area',
 124: 'Fayetteville, NC Metro Area',
 83: 'Winston-Salem, NC Metro Area',
 257: 'Rocky Mount, NC Metro Area',
 63: 'Raleigh-Cary, NC Metro Area',
 81: 'Greensboro-High Point, NC Metro Area',
 203: 'Wilmington, NC Metro Area',
 295: 'Jacksonville, NC Metro Area',
 288: 'Greenville, NC Metro Area',
 343: 'Goldsboro, NC Metro Area',
 338: 'Bismarck, ND Metro Area',
 297: 'Lima, OH Metro Area',
 205: 'Wheeling, WV-OH Metro Area',
 115: 'Canton-Massillon, OH Metro Area',
 220: 'Springfield, OH Metro Area',
 23: 'Cleveland-Elyria, OH Metro Area',
 29: 'Columbus, OH Metro Area',
 66: 'Toledo, OH Metro Area',
 58: 'Dayton-Kettering, OH Metro Area',
 244: 'Weirton-Steubenville, WV-OH Metro Area',
 68: 'Youngstown-Warren-Boardman, OH-PA Metro Area',
 64: 'Akron, OH Metro Area',
 292: 'Mansfield, OH Metro Area',
 38: 'Oklahoma City, OK Metro Area',
 303: 'Lawton, OK Metro Area',
 52: 'Tulsa, OK Metro Area',
 380: 'Enid, OK Metro Area',
 370: 'Corvallis, OR Metro Area',
 26: 'Portland-Vancouver-Hillsboro, OR-WA Metro Area',
 319: 'Bend, OR Metro Area',
 236: 'Medford, OR Metro Area',
 377: 'Grants Pass, OR Metro Area',
 137: 'Eugene-Springfield, OR Metro Area',
 320: 'Albany-Lebanon, OR Metro Area',
 151: 'Salem, OR Metro Area',
 376: 'Gettysburg, PA Metro Area',
 19: 'Pittsburgh, PA Metro Area',
 132: 'Reading, PA Metro Area',
 253: 'Altoona, PA Metro Area',
 221: 'Johnstown, PA Metro Area',
 281: 'State College, PA Metro Area',
 355: 'Bloomsburg-Berwick, PA Metro Area',
 93: 'Harrisburg-Carlisle, PA Metro Area',
 155: 'Erie, PA Metro Area',
 304: 'Chambersburg-Waynesboro, PA Metro Area',
 77: 'Scranton--Wilkes-Barre, PA Metro Area',
 104: 'Lancaster, PA Metro Area',
 321: 'Lebanon, PA Metro Area',
 254: 'Williamsport, PA Metro Area',
 293: 'East Stroudsburg, PA Metro Area',
 105: 'York-Hanover, PA Metro Area',
 70: 'Greenville-Anderson, SC Metro Area',
 241: 'Hilton Head Island-Bluffton, SC Metro Area',
 89: 'Charleston-North Charleston, SC Metro Area',
 75: 'Columbia, SC Metro Area',
 283: 'Sumter, SC Metro Area',
 193: 'Florence, SC Metro Area',
 168: 'Spartanburg, SC Metro Area',
 191: 'Sioux Falls, SD Metro Area',
 326: 'Rapid City, SD Metro Area',
 71: 'Knoxville, TN Metro Area',
 356: 'Cleveland, TN Metro Area',
 39: 'Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area',
 232: 'Johnson City, TN Metro Area',
 227: 'Jackson, TN Metro Area',
 301: 'Morristown, TN Metro Area',
 158: 'Kingsport-Bristol, TN-VA Metro Area',
 237: 'Wichita Falls, TX Metro Area',
 163: 'Amarillo, TX Metro Area',
 30: 'San Antonio-New Braunfels, TX Metro Area',
 10: 'Houston-The Woodlands-Sugar Land, TX Metro Area',
 40: 'Austin-Round Rock-Georgetown, TX Metro Area',
 139: 'Killeen-Temple, TX Metro Area',
 207: 'College Station-Bryan, TX Metro Area',
 210: 'Abilene, TX Metro Area',
 156: 'Brownsville-Harlingen, TX Metro Area',
 5: 'Dallas-Fort Worth-Arlington, TX Metro Area',
 159: 'Lubbock, TX Metro Area',
 264: 'Odessa, TX Metro Area',
 69: 'El Paso, TX Metro Area',
 178: 'Waco, TX Metro Area',
 349: 'Victoria, TX Metro Area',
 298: 'Sherman-Denison, TX Metro Area',
 157: 'Longview, TX Metro Area',
 111: 'Beaumont-Port Arthur, TX Metro Area',
 101: 'McAllen-Edinburg-Mission, TX Metro Area',
 278: 'San Angelo, TX Metro Area',
 274: 'Midland, TX Metro Area',
 127: 'Corpus Christi, TX Metro Area',
 231: 'Tyler, TX Metro Area',
 214: 'Laredo, TX Metro Area',
 100: 'Ogden-Clearfield, UT Metro Area',
 98: 'Provo-Orem, UT Metro Area',
 54: 'Salt Lake City, UT Metro Area',
 374: 'St. George, UT Metro Area',
 208: 'Burlington-South Burlington, VT Metro Area',
 218: 'Charlottesville, VA Metro Area',
 49: 'Richmond, VA Metro Area',
 187: 'Lynchburg, VA Metro Area',
 306: 'Staunton, VA Metro Area',
 161: 'Roanoke, VA Metro Area',
 316: 'Winchester, VA-WV Metro Area',
 250: 'Blacksburg-Christiansburg, VA Metro Area',
 345: 'Harrisonburg, VA Metro Area',
 172: 'Kennewick-Richland, WA Metro Area',
 323: 'Wenatchee, WA Metro Area',
 305: 'Longview, WA Metro Area',
 14: 'Seattle-Tacoma-Bellevue, WA Metro Area',
 199: 'Bremerton-Silverdale-Port Orchard, WA Metro Area',
 340: 'Mount Vernon-Anacortes, WA Metro Area',
 97: 'Spokane-Spokane Valley, WA Metro Area',
 194: 'Olympia-Lacey-Tumwater, WA Metro Area',
 381: 'Walla Walla, WA Metro Area',
 310: 'Bellingham, WA Metro Area',
 204: 'Yakima, WA Metro Area',
 146: 'Charleston, WV Metro Area',
 289: 'Beckley, WV Metro Area',
 224: 'Morgantown, WV Metro Area',
 346: 'Parkersburg-Vienna, WV Metro Area',
 162: 'Green Bay, WI Metro Area',
 192: 'Appleton, WI Metro Area',
 251: 'Eau Claire, WI Metro Area',
 88: 'Madison, WI Metro Area',
 318: 'Fond du Lac, WI Metro Area',
 235: 'Wausau-Weston, WI Metro Area',
 32: 'Milwaukee-Waukesha, WI Metro Area',
 202: 'Racine, WI Metro Area',
 247: 'Janesville-Beloit, WI Metro Area',
 369: 'Sheboygan, WI Metro Area',
 230: 'Oshkosh-Neenah, WI Metro Area',
 353: 'Cheyenne, WY Metro Area',
 378: 'Casper, WY Metro Area'}

In [47]:
msa_list = df['MSA ABBREVIATED NAME'].tolist()

In [100]:
msa_sim = []
for x in msa_list:
    first = x.split(',')[0].lower()
    state = x.split(',')[1]
    state = state[1:3]
    first = first.split('-')[0]
    first = first.split('/')[0]
    msa_sim.append([first, state])

In [101]:
msa_sim

[['phoenix', 'AZ'],
 ['tucson', 'AZ'],
 ['los angeles', 'CA'],
 ['riverside', 'CA'],
 ['sacramento', 'CA'],
 ['san diego', 'CA'],
 ['san francisco', 'CA'],
 ['san jose', 'CA'],
 ['denver', 'CO'],
 ['hartford', 'CT'],
 ['washington', 'DC'],
 ['miami', 'FL'],
 ['jacksonville', 'FL'],
 ['orlando', 'FL'],
 ['tampa', 'FL'],
 ['atlanta', 'GA'],
 ['chicago', 'IL'],
 ['indianapolis', 'IN'],
 ['louisville', 'KY'],
 ['new orleans', 'LA'],
 ['baltimore', 'MD'],
 ['worcester', 'MA'],
 ['boston', 'MA'],
 ['detroit', 'MI'],
 ['minneapolis', 'MN'],
 ['st. louis', 'MO'],
 ['kansas city', 'MO'],
 ['omaha', 'NE'],
 ['las vegas', 'NV'],
 ['albuquerque', 'NM'],
 ['albany', 'NY'],
 ['buffalo', 'NY'],
 ['rochester', 'NY'],
 ['new york', 'NY'],
 ['raleigh', 'NC'],
 ['charlotte', 'NC'],
 ['cleveland', 'OH'],
 ['columbus', 'OH'],
 ['cincinnati', 'OH'],
 ['oklahoma city', 'OK'],
 ['tulsa', 'OK'],
 ['portland', 'OR'],
 ['pittsburgh', 'PA'],
 ['philadelphia', 'PA'],
 ['providence', 'RI'],
 ['nashville', 'TN'],
 ['austin', 'TX'],
 ['dallas', 'TX'],
 ['houston', 'TX'],
 ['san antonio', 'TX'],
 ['salt lake city', 'UT'],
 ['richmond', 'VA'],
 ['virginia beach', 'VA'],
 ['seattle', 'WA'],
 ['milwaukee', 'WI']]

In [102]:
shared_msa = []
for i in data.items():
    name = i[1].split(',')[0].lower()
    name = name.split('-')[0]
    st = i[1].split(',')[1][1:3]
    for n in msa_sim:
        if name == n[0] and st == n[1]:
            shared_msa.append(i[0])

In [104]:
shared_msa

[12,
 56,
 11,
 28,
 2,
 16,
 36,
 22,
 21,
 43,
 53,
 4,
 7,
 50,
 8,
 18,
 46,
 13,
 17,
 3,
 33,
 24,
 47,
 25,
 37,
 20,
 34,
 9,
 6,
 15,
 31,
 1,
 62,
 51,
 41,
 45,
 27,
 35,
 63,
 23,
 29,
 38,
 52,
 26,
 19,
 39,
 30,
 10,
 40,
 5,
 54,
 49,
 14,
 32]

In [60]:
from difflib import SequenceMatcher

def similar(a, b):
    return SequenceMatcher(None, a, b).ratio()

In [63]:
similar("Phoenix-Mesa-Scottsdale","Phoenix-Mesa")

0.6857142857142857